version: '3.9'
services:
  db-staging:
    container_name: container-pg-staging
    build: ./postgres-build
    hostname: db-staging
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_STAGING_PORT}:5432
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
    restart: unless-stopped
  db-production:
    container_name: container-pg-production
    build: ./postgres-build
    hostname: db-production
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PRODUCTION_PORT}:5432
    volumes:
      - postgres-production-data:/var/lib/postgresql/data
    restart: unless-stopped
  backend-staging:
    container_name: container-backend-staging
    build: ${BACKEND_STAGING_REPO}
    hostname: ${HOST_NAME}
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=staging
    ports:
      - ${BACKEND_STAGING_PORT}:8080
    restart: unless-stopped
  backend-production:
    container_name: container-backend-production
    build: ${BACKEND_PRODUCTION_REPO}
    hostname: ${HOST_NAME}
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=production
    ports:
      - ${BACKEND_PRODUCTION_PORT}:8080
    restart: unless-stopped
  frontend-staging:
    container_name: container-frontend-staging
    build: ${FRONTEND_STAGING_REPO}
    hostname: ${HOST_NAME}
    env_file:
      - ./.env
    environment:
      - REACT_APP_ENVIRONMENT=staging
    ports:
        - ${FRONTEND_STAGING_PORT}:3000
    restart: unless-stopped
  frontend-production:
    container_name: container-frontend-production
    build: ${FRONTEND_PRODUCTION_REPO}
    hostname: ${HOST_NAME}
    env_file:
      - ./.env
    environment:
        - REACT_APP_ENVIRONMENT=production
    ports:
        - ${FRONTEND_PRODUCTION_PORT}:3000
    restart: unless-stopped
  nginx:
    container_name: container-nginx
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-production
      - backend-staging
      - frontend-production
      - frontend-staging
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./nginx/webroot:/var/www/html
      - ./certificates:/etc/letsencrypt:ro
  certbot:
    container_name: container-certbot
    image: certbot/certbot
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/webroot:/var/www/html
      - ./certificates:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email jwood@swood.org --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d mytexas42.com -d www.mytexas42.com -d app.mytexas42.com -d www.app.mytexas42.com -d staging-app.mytexas42.com -d www.staging-app.mytexas42.com -d api.mytexas42.com -d www.api.mytexas42.com -d staging-api.mytexas42.com -d www.staging-api.mytexas42.com
  

volumes:
  postgres-staging-data:
  postgres-production-data: